[[repo]]
    org = "mozilla-mobile"
    name = "android-components"
    branch = "master"

[[repo]]
    org = "mozilla-mobile"
    name = "fenix"
    branch = "master"

[[repo]]
    org = "mozilla-mobile"
    name = "firefox-tv"
    branch = "master"

[[repo]]
    org = "MozillaReality"
    name = "FirefoxReality"
    branch = "master"

[[repo]]
    org = "mozilla-lockwise"
    name = "lockwise-android"
    branch = "master"
