name: Update Spanish (es)
on:
  schedule:
    - cron: '0 7 * * 1-5' # Run Mon-Fri at 7AM UTC
  workflow_dispatch:

jobs:
  copy:
    name: Copy translations
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Copy translations from es-ES to es
        run: |
          python .github/scripts/copy_locale.py --source es-ES --dest es --path mozilla-mobile/android-components
          python .github/scripts/copy_locale.py --source es-ES --dest es --path mozilla-mobile/fenix
      - run : git config --global user.email 'flodolo@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update Spanish (es) localizations"
          branch: l10n_spanish
          delete-branch: true
          title: "Update Spanish (es) localizations"
